sudo: required
language: node_js
node_js: 8.12.0

services: docker

stages:
- name: Precache
- name: Lint
- name: Deploy to Heroku

cache:
  directories:
    - node_modules

jobs:
  fast_finish: true
  include:
  - stage: Precache
    script: true
    install: npm i
  - stage: Lint
    skip_cleanup: true
    script: npm run lint  
  - stage: Deploy to Heroku
    script: echo "npm test disabled"
    deploy:
      - provider: script
        script: ./deploy.sh
        skip_cleanup: true
        on:
          branch: master